MODEL_2D:
#  TYPE: "ViT-B-16"
  TYPE: "ViT-L-14"
  NUM_CLASSES: 10
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 10
  DUAL_HEAD: True
#  SCN:
#    in_channels: 3  # PS: rgb info as point feature (default=1)
DATASET_SOURCE:
  TYPE: "A2D2SCN"
  TRAIN: ("train",)
  A2D2SCN:
    preprocess_dir: "a2d2/a2d2_intensity_preprocess/"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: 'kitti/data_odometry_intensity_preprocess/preprocess/'
    semantic_kitti_dir: 'kitti/'
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (120000, 135000) # (80000, 90000) for ViT-B-16; (120000, 135000) for ViT-L-14
  MAX_ITERATION: 150000 # 100000 for ViT-B-16; 150000 for ViT-L-14
TRAIN:
  BATCH_SIZE: 4 # 8 (for ViT-B-16); 4 (for ViT-L-14)
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 7500 # 5000 (for ViT-B-16); 7500 (for ViT-L-14)
  CLASS_WEIGHTS: [1.89090012, 2.0585112, 3.1970535, 3.1111633, 1., 2.93751704, 1.92053733,
                  1.47886874, 1.04654198, 1.78266561]
  XMUDA:
    lambda_xm_src: 0.1
VAL:
  BATCH_SIZE: 1
  PERIOD: 7500 # 5000 (for ViT-B-16); 7500 (for ViT-L-14)

OUTPUT_DIR: "/output/a2d2_skitti/dg/ViT-L-14/"
