MODEL_2D:
#  TYPE: "ViT-B-16"
  TYPE: "ViT-L-14"
  NUM_CLASSES: 6
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_usa",)
  NuScenesLidarSegSCN:
    preprocess_dir: "nuscenes/nuscenes_lidarseg_preprocess_merge/preprocess"
    nuscenes_dir: "nuscenes" # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesLidarSegSCN:
    preprocess_dir: "nuscenes/nuscenes_lidarseg_preprocess_merge/preprocess"
    nuscenes_dir: "nuscenes"  # only front cam images are needed
DATALOADER:
  NUM_WORKERS: 8
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (40000, 50000)
  MAX_ITERATION: 60000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.9241476, 1., 2.16763851, 2.78254323, 1.54875664, 1.85686537]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000

OUTPUT_DIR: "output/usa_singapore/da/ViT-L-14/"
