MODEL_2D:
#  TYPE: "ViT-B-16"
  TYPE: "ViT-L-14"
  NUM_CLASSES: 6
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 6
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesLidarSegSCN"
  TRAIN: ("train_singapore",)
  NuScenesLidarSegSCN:
    preprocess_dir: "nuscenes/nuscenes_lidarseg_intensity_preprocess/preprocess/preprocess"
    nuscenes_dir: "nuscenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesLidarSegSCN"
  VAL: ("test_usa",)
  TEST: ("test_usa",)
  NuScenesLidarSegSCN:
    preprocess_dir: "nuscenes/nuscenes_lidarseg_intensity_preprocess/preprocess/preprocess"
    nuscenes_dir: "nuscenes"  # only front cam images are needed
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (40000, 50000)
  MAX_ITERATION: 60000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.07738526, 1., 1.91570733, 1.65574496, 1.48447244, 1.23336500]
  XMUDA:
    lambda_xm_src: 1.0
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000

OUTPUT_DIR: "output/singapore_usa/dg/ViT-L-14/"
